### ISSUE TITLE
build 问题

### ISSUE THREAD

**Issue by ChenWeihua123** [tolking/element-pro-components#118]
这个项目我打包的有一些问题
lib文件夹中没有 styles 文件夹，并且 buid 时会报一大堆 element 类型错误

请问我应该怎么正确的打包，希望大佬帮忙看下

我使用命令 npm run build

![image](https://user-images.githubusercontent.com/33150900/135045405-30bd61d6-e084-49cb-a9fd-868ab1f4f37b.png)

![image](https://user-images.githubusercontent.com/33150900/135045455-c6bf261c-25f0-4640-bd62-f3b02a12ff50.png)

**Comment by ChenWeihua123** [comment]
sorry.. 我用的是 windows, fast-glob 需要简单修改一下嘿嘿

这个 /node_moduls/element-plus 类型报错怎么消除

**Comment by tolking** [comment]
element-plus 正在重构类型，等待直接引用其内部相关类型重构完成，或许就没有报错了。要想现在没有报错要重构相关类型，比较费时间
