### ISSUE TITLE
组件使用时报错，页面无内容

### ISSUE THREAD

**Issue by ChenWeihua123** [tolking/element-pro-components#119]
在此叨扰，element-pro-components@0.13.1 vue@3.2.1

全局注册时 ts error:
![image](https://user-images.githubusercontent.com/33150900/135088255-09de376d-2ef8-4f22-90fd-e02efc95c11e.png)

vue文件中引入组件报如下异常，项目无法运行
![image](https://user-images.githubusercontent.com/33150900/135088137-636c4a4b-3b2e-43c1-b4ca-61d313f323e8.png)

element-plus@1.1.0-beta.8 ，之后升级到最新版都不行
请教下大家都是如何使用的，我第一次用这个组件库，很棒的库

**Comment by tolking** [comment]
提供一个最小的错误呈现，将更利于我排错。现在我也不好判断错误出现在那里

**Comment by tolking** [comment]
或者提供报错页面的代码部分

**Comment by ChenWeihua123** [comment]
@tolking [ts在线地址](https://codesandbox.io/s/agitated-pasteur-i70jt?file=/src/index.ts)
我发现 js 版本没出现问题，ts的就有这个问题

**Comment by tolking** [comment]
我问下是否是从一个完整的脚手架开始项目，或者注释 element-pro-components 相关代码，仅使用 plus 组件看是否依旧报错。

**Comment by ChenWeihua123** [comment]
![image](https://user-images.githubusercontent.com/33150900/135227732-9a93b37e-bec2-4bcc-bd6c-f87cab2fdf65.png)
这个演示里只要把这行删掉就不报错了

我的项目是通过一个完整的脚手架创建的项目，模板中不使用 element-pro-components 组件就没有错误，plus 组件正常使用。我很苦恼。。折腾一天没折腾明白

您看看我还需要提供什么

**Comment by tolking** [comment]
修改成 el-button 也会报错。plus 和 当前组件都用了大量 setup 函数，或许与动态解析模版不兼容。
脚手架是基于 vite 还是 vue-cli

**Comment by ChenWeihua123** [comment]
cli

**Comment by ChenWeihua123** [comment]
这个 demo plus 组件确实报错了，但是我的项目中plus组件正常跑的

这个demo没问题[js cli demo](https://codesandbox.io/s/pedantic-lake-5w1kf)

**Comment by tolking** [comment]
这个 dome pro-crud 没有报错啊

**Comment by ChenWeihua123** [comment]
对啊  所以我更摸不清头脑了，这是 js 版本的， 我项目是 ts 的就报错了，真的头大

**Comment by tolking** [comment]
直接 `<script lang="ts">` 也不会有问题啊

**Comment by ChenWeihua123** [comment]
哎我也不知道啥问题了， 我有时间重新cli一个项目测试一下吧，感谢作者帮助

**Comment by tolking** [comment]
或者尝试 vite

**Comment by ChenWeihua123** [comment]
还是同一个项目，我升级了  vue 到最新的 3.2.19 ，正常运行了，并且我上面提到的 **app.use(ElementPro)** _typescript_ 类型 _error_  也消除了

有问题的 vue 版本是 3.2.1 ，可能这个版本 script setup 的使用有一些问题吧，只是猜测具体原因不知。pro 组件没有问题。

这个 issues 可以关掉了

**Comment by tolking** [comment]
原来是版本问题，感谢你的反馈
