### ISSUE TITLE
我看项目里面有很多h函数，是什么考虑没有使用jsx呢

### ISSUE THREAD

**Issue by xlzy520** [tolking/element-pro-components#297]
个人认为jsx可读性更好一点，写起来也方便

**Comment by tolking** [comment]
其实项目最开始是采用 setup + .vue 单文件构建的。但由于组件在当时无法设置 name 属性，同时没有适合的工具生成 ts 类型。后来才换到现在这种形式。

没有采用 jsx 其实就是因为我之前没有用过，有需要都是直接写 h() 函数。我用 h() 函数反而写着方便。

vue 单文件、tsx、h() 等都是工具而已，需要什么就用什么

**Comment by xlzy520** [comment]
vite pugin setup name extend这个插件可以设置name

工具是这样，我最开始也是不知道jsx，用的h，后面了解到才换过去的

**Comment by xlzy520** [comment]
我上家公司和你这个做的是基本一样的，是Vue2的elementUI
不过我认为你这个要好特别多，所以找了过来，也给群友推荐了几次，哈哈
