### ISSUE TITLE
CRUD pro-select 怎么加入左侧图标，默认卡槽无效

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-pro-components#339]
```
{
    label: '图标',
    prop: 'icon',
    component: 'pro-select',
    props: {
      data: selectIcon.value,
      config: config.value,
      defaults: (item:any) => h(' span',
        null,
        ‘66666’,
      ),

    },
```

![Screenshot from 2022-07-11 16-31-00](https://user-images.githubusercontent.com/40333954/178222297-625f4303-0589-4d0a-b535-14a8cbf6dc1c.png)
![Screenshot from 2022-07-11 16-32-23](https://user-images.githubusercontent.com/40333954/178222479-d3d03cd3-53c8-41f4-9c25-ce522b4a4c8a.png)

**Comment by tolking** [comment]
config: config.value,
slots: {
      defaults: (item...
}

类似这样吧，这样可以使用插槽，但最好使用模版里面的插槽。

**Comment by InfernalAzazel** [comment]
> config: config.value, slots: { defaults: (item... }
> 
> 类似这样吧，这样可以使用插槽，但最好使用模版里面的插槽。

这个方法没有作用，不过我已经用其他方法实现了

**Comment by InfernalAzazel** [comment]
解决方法:

ExSelect 是我用el-select 重新封装的一个组件
```
{
    label: '图标',
    prop: 'icon',
    component: markRaw(ExSelect),
    props: {
      data: selectIcon.value,
    },
```
