### ISSUE TITLE
CRUD 能否实现拖动表头列来调节宽度

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-pro-components#357]
经过内部测试 这个需求还满多的

调研原因: 赛选效率

**Comment by tolking** [comment]
自己看文档吧，我记得 table 有个参数可以控制是否可以拖动列。这里缺失就去 element-plus 找找

**Comment by InfernalAzazel** [comment]
> 自己看文档吧，我记得 table 有个参数可以控制是否可以拖动列。这里缺失就去 element-plus 找找

谢谢
