### ISSUE TITLE
columns 动态赋值问题

### ISSUE THREAD

**Issue by muchenfine** [tolking/element-pro-components#371]
如果配置表单项columns，如果columns里的某个select的数据是后台接口返回的， 应该如何操作，通过column[2] 这种索引方式吗 ？

**Comment by tolking** [comment]
如果 columns 是一个响应式数组，当然你可以这样做。但也可以[这样做](https://tolking.github.io/element-pro-components/zh-CN/components/form#%E5%BC%82%E6%AD%A5%E8%A1%A8%E5%8D%95)

**Comment by tolking** [comment]
对，只有 column 具有响应式，其内部的变动才能够影响界面变动。

如果 column 是固定的，可以为 pro-form 增加 `v-once`，这样理论上性能更好些，同时 select 的数据也可以随时改动

**Comment by tolking** [comment]
form 不会变动，但如果 ProSelect 引用的是响应式数据，数据变了会影响内容变动

**Comment by tolking** [comment]
自己封装 select 组件，通过外部传递 api 地址或其他参数。内部自己实现数据的处理。这种与业务强关联，可能无法在不同项目间通用

**Comment by tolking** [comment]
对

**Comment by tolking** [comment]
我推荐 ref
