### ISSUE TITLE
pro-descriptions 如果内容比较长标签会挤压在一起中文还可以英文就很难看了

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-pro-components#372]
![屏幕截图 2022-09-01 11:45:10](https://user-images.githubusercontent.com/40333954/187827289-006856ed-9e26-487b-9ce7-1b51da20bc6b.png)

我希望能够标签名称能保证一定的宽度

**Comment by tolking** [comment]
`labelClassName`
