### ISSUE TITLE
CRUD form 自定义时间控件怎么 setValue,提交后端一直是null 值

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-pro-components#375]
![微信截图_20220916180106](https://user-images.githubusercontent.com/40333954/190614461-eaca551e-4b05-456f-8d59-bde083f3eddd.png)

![微信截图_20220916180243](https://user-images.githubusercontent.com/40333954/190614539-46dffcc6-3257-4af9-8f5f-99d1d1b8c5f4.png)

code
```
<template #form-get_time="{ item, value, setValue }">
        <el-date-picker
            v-model="getTime"
            type="date"
            :default-value="value"
            placeholder="Pick a day"
            @change="setValue = getTime.value"
        />
      </template>
```

**Comment by tolking** [comment]
setValue 是一个函数

**Comment by InfernalAzazel** [comment]
> setValue 是一个函数

不起作用啊
