### ISSUE TITLE
How to build docs

### ISSUE THREAD

**Issue by freshzxf** [tolking/element-pro-components#395]
When I run dev and open component documentation or run build:docs, It always reminds me
Rollup failed to resolve import "E:Projectsexercisewebelement-pro-components/demo/Layout/base.vue" from "docs/docs/en-US/components/Layout.md".
![image](https://user-images.githubusercontent.com/28848999/196015173-23b87d0a-3456-4405-9de2-abecca546bdd.png)
Can you help me find out why?

**Comment by tolking** [comment]
Maybe you can try updating the code and updating the dependencies.

**Comment by tolking** [comment]
win ? 看起来像是 rawPath 路径错误了

**Comment by tolking** [comment]
试试

```ts
const rawPath = toAbsolute(link.replace(/^@/, '..'))
```

**Comment by freshzxf** [comment]
是的，win10环境，node版本16.16.0，pnpm版本7.13.0，按照上面的改了（demo.ts的第31行）重启运行依然报错，这个问题困扰我蛮多天了，不确定哪里出问题了，还请帮忙看下哪个环境出错了... ...

> 试试
> 
> ```ts
> const rawPath = toAbsolute(link.replace(/^@/, '..'))
> ```

**Comment by tolking** [comment]
一样的错误？或者你可以打印相关值看看，我没有win，无法测试

试试

```ts
const rawPath = link.replace(/^@/, '..')
```

**Comment by freshzxf** [comment]
好的 OK
