### ISSUE TITLE
【bug】通过babel-plugin-import进行按需引入组件报错无法找到

### ISSUE THREAD

**Issue by Yxiuchao** [tolking/element-pro-components#411]
## 版本
1.2.3

## 现象

![image](https://user-images.githubusercontent.com/48636987/198879076-323ed706-2fa3-452c-bc7e-15fe213f21db.png)

## 描述：

通过安装babel-plugin-impor进行按需引入，并按照官网提示配置
```
plugins: [
    [
      'import',
      {
        libraryName: 'element-pro-components',
        customStyleName: (name) => {
          return `element-pro-components/lib/styles/${name.slice(4)}`
        },
      },
    ],
  ]
```
## 原因
通过查看[babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import)进行转换方法,对于组件的引入会解析到`包名/lib/组件名`如下所示
```
import { Button } from 'antd';
ReactDOM.render(<Button>xxxx</Button>);

      ↓ ↓ ↓ ↓ ↓ ↓

var _button = require('antd/lib/button');
ReactDOM.render(<_button>xxxx</_button>);
```
然而element-pro-component组件构建后的组件的js却放到了`lib/styles/`下了
![image](https://user-images.githubusercontent.com/48636987/198879311-97199f97-93c6-4a27-8140-7b04c8301dd3.png)
![image](https://user-images.githubusercontent.com/48636987/198879321-ff4d3b1d-6036-4ca3-b854-d833963acd43.png)

**Comment by tolking** [comment]
应该缺少 `customName ` 配置, js 只有一个文件，styles 里面是样式

```diff
plugins: [
    [
      'import',
      {
        libraryName: 'element-pro-components',
+       customName: () => 'element-pro-components',
        customStyleName: (name) => {
          return `element-pro-components/lib/styles/${name.slice(4)}`
        },
      },
    ],
  ]
```

**Comment by Yxiuchao** [comment]
> 应该缺少 `customName ` 配置, js 只有一个文件，styles 里面是样式
> 
> ```diff
> plugins: [
>     [
>       'import',
>       {
>         libraryName: 'element-pro-components',
> +       customName: () => 'element-pro-components',
>         customStyleName: (name) => {
>           return `element-pro-components/lib/styles/${name.slice(4)}`
>         },
>       },
>     ],
>   ]
> ```
![image](https://user-images.githubusercontent.com/48636987/198881049-f714c0bb-eeca-428c-b802-c4a92e097ec8.png)

加上依然会报错，我觉得不是这个原因，因为看[babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import)的解析方式来说,在按照当前配置后他最终会将引入的转换为如下格式:
```
import { ProCard } from 'element-pro-components';

      ↓ ↓ ↓ ↓ ↓ ↓

var proCard= require(''element-pro-components/lib/pro-card');
require(''element-pro-components/lib/styles/pro-card');
```

**Comment by tolking** [comment]
加了 `customName ` 应该就变为 

```
var proCard= require('element-pro-components');
require('element-pro-components/lib/styles/pro-card');
```

**Comment by Yxiuchao** [comment]
> 加了 `customName ` 应该就变为
> 
> ```
> var proCard= require('element-pro-components');
> require('element-pro-components/lib/styles/pro-card');
> ```

+1 我也这么认为，但是事实却不是，我尝试过这个直接写成一个function返回一个固定的路径，但是还是没有作用，等我明天下班了再看看🌝

**Comment by tolking** [comment]
如果这样也不行，可能就无法使用 babel-plugin-import

推荐使用 [unplugin-vue-components](https://www.npmjs.com/package/unplugin-vue-components)

**Comment by Yxiuchao** [comment]
> 如果这样也不行，可能就无法使用 babel-plugin-import
> 
> 推荐使用 [unplugin-vue-components](https://www.npmjs.com/package/unplugin-vue-components)

在vue文件的script中声明components则没有问题,如果是设置setup的script的则无法解析到

这种形式的可以正常加载
```vue
<script lang="ts">
import { ProCard } from 'element-pro-components';

export default {
  components: {
    ProCard
  }
}
</script>
```

这种的则无法解析到
<script setup lang="ts">
import { ProCard } from 'element-pro-components';

</script>

**Comment by tolking** [comment]
使用 unplugin-vue-components 不需要在 .vue 文件中引用组件。详细可以看 [Template](https://github.com/tolking/element-admin-template)

```diff
<script setup lang="ts">
- import { ProCard } from 'element-pro-components';
</script>
```

**Comment by Yxiuchao** [comment]
> 使用 unplugin-vue-components 不需要在 .vue 文件中引用组件。详细可以看 [Template](https://github.com/tolking/element-admin-template)
> 
> ```diff
> <script setup lang="ts">
> - import { ProCard } from 'element-pro-components';
> </script>
> ```

我能说他是全量引入的嘛  
[vue-admin-template](https://github.com/tolking/element-admin-template/blob/main/src/main.ts#L14)

**Comment by tolking** [comment]
我忘记之前移除了
