### ISSUE TITLE
vue3 yarn add element-pro-components error

### ISSUE THREAD

**Issue by yasminyt** [tolking/element-pro-components#450]
### Describe the bug

An unexpected error occurred: "expected hoisted manifest for \"element-pro-components#vue#@vue/server-renderer#@vue/compiler-ssr\"".

### Related version

"dependencies": {
    "element-plus": "^2.2.9",
    "unplugin-auto-import": "^0.9.3",
    "unplugin-vue-components": "^0.21.1",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.0",
    "vite": "^3.0.0"
  }

element-pro-components latest

### Steps to Reproduce the Bug

yarn add element-pro-components

### Expected behavior

install package success

**Comment by tolking** [comment]
You can try to install element-pro-components through npm first. It may be Yarn's fault 🤔

**Comment by yasminyt** [comment]
> 

用npm可以安装，但是运行项目时是报错的
<img width="1746" alt="企业微信截图_fbb6d05e-673a-4897-8650-832c9e500551" src="https://user-images.githubusercontent.com/33113542/219253264-f4f8a2c4-e8e0-47e5-a0dd-d91c75240eb9.png">

另外文档上写的
import 'element-pro-components/lib/styles/index'
我看包中的目录结构里已经没有 styles 这个目录
<img width="339" alt="image" src="https://user-images.githubusercontent.com/33113542/219253490-ce713554-38db-4c22-96eb-626a759a19a2.png">

安装下来的版本为 "element-pro-components": "^1.5.0"

**Comment by tolking** [comment]
最新版是 1.2.9 。

这1.5.0难道是我之前发错的版本号，我记得从npm中删除了啊

**Comment by yasminyt** [comment]
> 
指定1.2.9版本进行安装，yarn和npm都可安装成功，但是yarn、npm安装时都是默认安装下来的是1.5.0

另外1.2.9的包里styles目录也是缺失的，目前无法正常引入样式文件
<img width="314" alt="image" src="https://user-images.githubusercontent.com/33113542/219287601-734c3497-5d4e-434e-ad57-95543ca9eff7.png">

运行还是会报错😂
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/33113542/219287902-872415bd-cfd7-4784-9318-ffffb2ddffbf.png">

只是一个普通的vue3项目，想测试下对本库的引用，后续打算在你的基础上继续扩展，因为代码结构什么的看起来很不错👍
// package.json
{
  "name": "vue3",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "element-plus": "^2.2.9",
    "element-pro-components": "^v1.2.9",
    "unplugin-auto-import": "^0.9.3",
    "unplugin-vue-components": "^0.21.1",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.0",
    "vite": "^3.0.0"
  }
}

**Comment by tolking** [comment]
yarn add element-pro-components@1.2.9

先安装指定版本吧，这个需要去 npm 看看

**Comment by yasminyt** [comment]
> 
用的是npm，，，

目前引入1.2.9版本的包，也无法正常启动项目，相关报错在前面的截图哈，麻烦看看咧

**Comment by tolking** [comment]
你可以查看 element-pro-components 目录下的 package.json 的版本，版本不对目录文件就不对

**Comment by yasminyt** [comment]
> 你可以查看 element-pro-components 目录下的 package.json 的版本，版本不对目录文件就不对

嗷嗷，昨天安装成了≥1.2.9，所以实际element-pro-components下的package.json还是1.5.0，导致上面所说的异常～

感谢耐心解答🫡
