### ISSUE TITLE
报错：在使用unplugin-vue-components 和 unplugin-auto-import这两款插件对element-plus进行按需引用时候

### ISSUE THREAD

**Issue by congwa** [tolking/element-pro-components#452]
### Describe the bug

![image](https://user-images.githubusercontent.com/26264441/226802410-502835d7-0509-437a-a241-ab835655ba16.png)
如果使用unplugin-vue-components 和 unplugin-auto-import这两款插件对element-plus进行按需引用，就会报如上错误。
您知道这是什么问题吗？ 
怎么样解决？

目前我的解决方式
![image](https://user-images.githubusercontent.com/26264441/226802611-87abfee7-0315-4c7b-af97-f3b783e6f3ee.png)
把element-plus全量引入了，就不报这个错误了

### Related version

vue 3.2.40

### Steps to Reproduce the Bug

如果使用unplugin-vue-components 和 unplugin-auto-import这两款插件对element-plus进行按需引用，就会报如上错误。
您知道这是什么问题吗？ 

### Expected behavior

期望能够按需引入，不报这个错误

**Comment by tolking** [comment]
element-plus 也需要配置按需加载
