### ISSUE TITLE
搜索和重置按钮添加图标没出现

### ISSUE THREAD

**Issue by lovesL** [tolking/element-pro-components#458]
### Describe the bug

添加图标没出现

### Related version

如链接

### Link to minimal reproduction

https://stackblitz.com/edit/2jiy3u?file=src%2FDemo.vue

### Steps to Reproduce the Bug

测试加个小图标没出现 我尝试改颜色 也没出来，链接里面我已经改好了代码

### Expected behavior

~

**Comment by lovesL** [comment]
![image](https://github.com/tolking/element-pro-components/assets/27960630/507ebff4-572a-43bf-9fef-1de9f193c246)
这个设置size没效果 小问题

**Comment by lovesL** [comment]
![image](https://github.com/tolking/element-pro-components/assets/27960630/e196a963-8514-48d6-ae54-1492314b9754)
这个查看里的内容能完全自定义内容吗大佬  产品说太丑了。。。 比如弹出类型编辑的表单 里面的内容不可编辑

**Comment by tolking** [comment]
Icon 传一个字符串，需要全局注册icon。

自己看文档中的插槽
