### ISSUE TITLE
table formatter无效

### ISSUE THREAD

**Issue by lovesL** [tolking/element-pro-components#483]
### Describe the bug

table formatter没触发

### Related version

    "element-plus": "^2.3.5",
    "element-pro-components": "^1.2.12",
    "vue": "3.2.45",

### Link to minimal reproduction

https://stackblitz.com/edit/yr12tg?file=src%2FDemo.vue

### Steps to Reproduce the Bug

链接

### Expected behavior

链接

**Comment by tolking** [comment]
formatter 无法在 ElTableColumn 存在默认插槽时触发。组件内部使用插槽使用一些功能，所以它无法使用。

可以使用相关 table-[prop] 插槽，或者使用 render
