### ISSUE TITLE
search-menu-right 插槽能改变下位置嘛

### ISSUE THREAD

**Issue by lovesL** [tolking/element-pro-components#488]
### Describe the bug

![image](https://github.com/tolking/element-pro-components/assets/27960630/d7f9f989-8e62-47cd-8f55-d92245256572)
![image](https://github.com/tolking/element-pro-components/assets/27960630/a4baa636-1ce8-42df-9efa-574620b210c8)
![image](https://github.com/tolking/element-pro-components/assets/27960630/5ca5ae58-5229-45bc-9ab9-12920c10bd5c)

这个两个能不能不放到一个form-content里面 

### Related version

    "element-plus": "^2.3.5",
    "element-pro-components": "^1.2.12",

### Steps to Reproduce the Bug

如上

### Expected behavior

如上

**Comment by tolking** [comment]
因为是基于ProForm，要保证ProForm的样式，是必须放在一个 content 里面

**Comment by tolking** [comment]
你也可以使用 search 插槽自定义按钮
