### ISSUE TITLE
array 类型报错is not a string

### ISSUE THREAD

**Issue by vine05** [tolking/element-pro-components#499]
### Describe the bug

![2023-12-11](https://github.com/tolking/element-pro-components/assets/42110402/e07cf257-bee5-42bf-a8f3-c30827462145)
![rules](https://github.com/tolking/element-pro-components/assets/42110402/4098fd7d-d0ce-4519-bcaf-79db75e19cf8)

UI 和 rules 如图。
填了array里头的内容，点击提交的时候报错说这个is not a string.

### Related version

element-pro-component: 1.2.12
vue: 3.3.4

### Steps to Reproduce the Bug

Create a array type in form.
Input value.
Click save.

### Expected behavior

Save succeed.

**Comment by tolking** [comment]
我没有复现这个问题，你可以参考文档中的 [Demo](https://tolking.github.io/element-pro-components/zh-CN/components/form#%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81)

**Comment by vine05** [comment]
我把这个array的required删掉，rules里已经没有它了，但是还是报同样的错误……疯了TAT

**Comment by vine05** [comment]
![uiColumnsWithEmptyButtons](https://github.com/tolking/element-pro-components/assets/42110402/e728a4bc-8401-44ab-b62b-a67961cc0e93)
我把其他组件都删除了，只保留了array这一项，并且把rules和childrens都清空了。但是在validate时还是报错。
图片上Buttons上面那一行就是columns打出来的值。

**Comment by tolking** [comment]
这是因为 [async-validator](https://github.com/yiminghe/async-validator?tab=readme-ov-file#type) 中 `type` 的默认值为 `string ` 引起的，传入 `{ type: 'array' }` 就没有问题
