### ISSUE TITLE
[BUG] pro-select  在搜索阶段样式变形，不会自适应大小

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-pro-components#514]
### Describe the bug

 pro-select  在搜索阶段样式变形

### Related version

@element-plus/icons-vue: "^2.3.1"
element-plu": "^2.5.6"
element-pro-components: "^1.2.12"
vue: "^3.4.15"
vite: "^5.0.11"

### Steps to Reproduce the Bug

只要把  pro-select 显示在搜索就会触发， el-select 也会。

### Expected behavior

正常

### Additional context

![2024-04-16 16-40-09 的屏幕截图](https://github.com/tolking/element-pro-components/assets/40333954/5a2c22a1-7435-42ce-a014-f1b9ad57afb7)

![2024-04-16 16-45-03 的屏幕截图](https://github.com/tolking/element-pro-components/assets/40333954/46d77147-1b52-44a3-97a3-c9b84dc2f688)

**Comment by tolking** [comment]
element-plus ElSelect的样式变了，现在需要增加自定义宽度

**Comment by InfernalAzazel** [comment]
> element-plus ElSelect的样式变了，现在需要增加自定义宽度

怎么增加?

**Comment by tolking** [comment]
```
.el-select {
  width: 400px
}
```
