### ISSUE TITLE
无法自定义命名空间

### ISSUE THREAD

**Issue by AAABingBing** [tolking/element-pro-components#523]
### Describe the bug

使用 [自动导入](https://element-plus.org/zh-CN/guide/quickstart.html#%E8%87%AA%E5%8A%A8%E5%AF%BC%E5%85%A5-%E6%8E%A8%E8%8D%90) 的方式使用 elementPlus 组件想要 [通过 SCSS 变量自定义主题](https://element-plus.org/zh-CN/guide/theming.html#%E9%80%9A%E8%BF%87-scss-%E5%8F%98%E9%87%8F) 必须 [自定义命名空间](https://element-plus.org/zh-CN/guide/namespace.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4) 否则会造成自定义样式与 API 组件样式冲突的问题

但 element-pro-components 并没有提供自定义命名空间的配置，导致 element-pro-components 所有组件样式无法生效

![image](https://github.com/user-attachments/assets/845b4896-e939-4fbf-9de4-c8395be8b205)

![image](https://github.com/user-attachments/assets/90a8da04-794d-465b-bc40-81c615050301)

### Related version

"vue": "^3.4.35"
"vite": "^5.3.5"
"element-plus": "^2.7.8"
"element-pro-components": "^1.3.1"

### Steps to Reproduce the Bug

/

### Expected behavior

添加自定义命名空间 namespce 配置项使得与 elementPlus 命名空间配置保持一致

**Comment by tolking** [comment]
目前仅支持通过 css-variables 同时控制两个组件库的变量。

由于这个组件库是采用原生的 CSS 编写的，所以无法支持命名空间

**Comment by AAABingBing** [comment]
> 目前仅支持通过 css-variables 同时控制两个组件库的变量。
> 
> 由于这个组件库是采用原生的 CSS 编写的，所以无法支持命名空间

明白，感谢您的回复
