### ISSUE TITLE
项目打包时，是否存在该问题

### ISSUE THREAD

**Issue by ghost** [tolking/element-pro-components#56]
node_modules/element-plus/lib/el-tree/src/model/node.d.ts:28:24 - error TS2304: Cannot find name 'Nullable'.

28     get nextSibling(): Nullable<Node>;
                          ~~~~~~~~

node_modules/element-plus/lib/el-tree/src/model/node.d.ts:29:28 - error TS2304: Cannot find name 'Nullable'.

29     get previousSibling(): Nullable<Node>;
                              ~~~~~~~~

node_modules/resize-observer-polyfill/src/index.d.ts:19:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'contentRect' must be of type 'DOMRectReadOnly', but here has type 'DOMRectReadOnly'.

19         readonly contentRect: DOMRectReadOnly;
                    ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:12696:14
    12696     readonly contentRect: DOMRectReadOnly;
                       ~~~~~~~~~~~
    'contentRect' was also declared here.

Found 3 errors.

node 16.0.0 环境

**Comment by tolking** [comment]
这是 element-plus 内部类型问题，部分全局类型没有很好导入引起。不是很重要，就没有改

**Comment by Jmysy** [comment]
希望参与开发，因为刚接触，所以问题会有点多

**Comment by Jmysy** [comment]
![image](https://user-images.githubusercontent.com/56584880/118791766-9d2f6b80-b8c9-11eb-8456-e3cc1734b916.png)

**Comment by Jmysy** [comment]
vite + ts 环境中，是否正常使用

**Comment by tolking** [comment]
欢迎！

我现在开发后台界面可以正常使用的，不过 vue-router和 element-plus 最好单独安装

**Comment by Jmysy** [comment]
明白，因为每个用户使用的版本不一致

**Comment by gorouter** [comment]
Hi, 能加入或探讨交流一下吗？加下tg: @wisleonn

**Comment by tolking** [comment]
@gorouter 可以
