### ISSUE TITLE
回复

### ISSUE THREAD

**Issue by ghost** [tolking/element-pro-components#75]
element-enhance 是 fork pro component , 并做了一些改动，和基于自己想法的拓展，会在近期删除原有 element pro component 代码，因个人对 MIT 协议了解不足，表示抱歉

**Comment by tolking** [comment]
恶心，还删我 issues

**Comment by jhdxr** [comment]
对比了下代码，删除相关代码基本上你可以直接删库开一个新的了

**Comment by francis-du** [comment]
其他先不说，请先把原作者 LICENSE 放回去。

**Comment by francis-du** [comment]
> 对比了下代码，删除相关代码基本上你可以直接删库开一个新的了
> 
> 

好家伙，代码已经删了😂

**Comment by yang-han** [comment]
> 会在近期删除原有 element pro component 代码

虽然我并不是想故意引战，但这句话真的好熟悉。。。。

**Comment by weisingxcw** [comment]
Mit项目小众/冷门，不代表你可以直接剽窃，删除作者署名，你注销账号吧，这个废了。（ Kilerd是你小号吧，V2ex红名单又丰富了）

**Comment by WildXBird** [comment]
华为行为

**Comment by xiaojia21190** [comment]
真是够恶心的

**Comment by dmwin72015** [comment]
我擦，我在看的issues的一突然有人提交了一个，github竟然是实时同步？？

**Comment by InfernalAzazel** [comment]
> Mit项目小众/冷门，不代表你可以直接剽窃，删除作者署名，你注销账号吧，这个废了。（ Kilerd是你小号吧，V2ex红名单又丰富了）

V2ex红名单是什么？
