### ISSUE TITLE
类型定义建议

### ISSUE THREAD

**Issue by chouchoui** [tolking/element-pro-components#77]
https://github.com/tolking/element-pro-components/blob/48de5176d7478f83e47d6dddfe76945888c067b5/src/types/form.ts#L84-L88

`invalidFields`的类型可以直接定义成
```typescript
interface InvalidFields {
  [prop: string]: { message: string; field: string }[];
}
```
  
  

因为`element plus`使用`async-validator`进行验证，可以进行如下定义
```typescript
import { RuleItem } from "async-validator";

type ElementRuleTrigger = "blur" | "change";
export type ElementRuleItem = RuleItem & { trigger: ElementRuleTrigger | ElementRuleTrigger[] };
```

https://github.com/tolking/element-pro-components/blob/48de5176d7478f83e47d6dddfe76945888c067b5/src/types/form.ts#L31
https://github.com/tolking/element-pro-components/blob/48de5176d7478f83e47d6dddfe76945888c067b5/src/types/form.ts#L13

以上两个interface中的 `rules` 的类型可改为 
```typescript
{
  rules: ElementRuleItem | ElementRuleItem[]
}
```

**Comment by tolking** [comment]
确实，这部分类型有待优化
